//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Panacea.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.2.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\ausefpdfs01ns\\Shares\\Public\\DC_Data\\Olympus\\QA\\Sol")]
        public string SolLocation {
            get {
                return ((string)(this["SolLocation"]));
            }
            set {
                this["SolLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("PK|SP PK|BLK PK")]
        public string IWMBZones {
            get {
                return ((string)(this["IWMBZones"]));
            }
            set {
                this["IWMBZones"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IWMBAllowSeparateUoMs {
            get {
                return ((bool)(this["IWMBAllowSeparateUoMs"]));
            }
            set {
                this["IWMBAllowSeparateUoMs"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("PK|SP PK|BLK PK")]
        public string BWMIZones {
            get {
                return ((string)(this["BWMIZones"]));
            }
            set {
                this["BWMIZones"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("PK|SP PK|PO PK|BLK PK|SUP PK|BLK SS|HR|PR|OS|OZ|PARK|REFURB|MC")]
        public string PurgeZones {
            get {
                return ((string)(this["PurgeZones"]));
            }
            set {
                this["PurgeZones"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("PK|SP PK|BLK SS|BLK PK|SUP PK|OS|PR|HR|ROX")]
        public string NegativeZones {
            get {
                return ((string)(this["NegativeZones"]));
            }
            set {
                this["NegativeZones"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("PK|SP PK|BLK SS|BLK PK|SUP PK|OS|PR|HR|ROX")]
        public string PotentNegZones {
            get {
                return ((string)(this["PotentNegZones"]));
            }
            set {
                this["PotentNegZones"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FBCFromZones {
            get {
                return ((string)(this["FBCFromZones"]));
            }
            set {
                this["FBCFromZones"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FBCFixedZones {
            get {
                return ((string)(this["FBCFixedZones"]));
            }
            set {
                this["FBCFixedZones"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("PK|SP PK|PO PK|BLK PK|SUP PK|BLK SS|CP|HR|PR|OS|PARK|REFURB|MC")]
        public string PickBinCheckZones {
            get {
                return ((string)(this["PickBinCheckZones"]));
            }
            set {
                this["PickBinCheckZones"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("9600")]
        public string PickBinCheckLocations {
            get {
                return ((string)(this["PickBinCheckLocations"]));
            }
            set {
                this["PickBinCheckLocations"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("9600")]
        public string BWMILocations {
            get {
                return ((string)(this["BWMILocations"]));
            }
            set {
                this["BWMILocations"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("9600")]
        public string IWMBLocations {
            get {
                return ((string)(this["IWMBLocations"]));
            }
            set {
                this["IWMBLocations"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("9600")]
        public string NegativeLocations {
            get {
                return ((string)(this["NegativeLocations"]));
            }
            set {
                this["NegativeLocations"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("9600")]
        public string PotentNegLocations {
            get {
                return ((string)(this["PotentNegLocations"]));
            }
            set {
                this["PotentNegLocations"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("9600")]
        public string PurgeLocations {
            get {
                return ((string)(this["PurgeLocations"]));
            }
            set {
                this["PurgeLocations"] = value;
            }
        }
    }
}
