//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Argos.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.2.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\ausefpdfs01ns\\Shares\\Public\\DC_Data\\Olympus\\QA\\Sol")]
        public string SolLocation {
            get {
                return ((string)(this["SolLocation"]));
            }
            set {
                this["SolLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\ausefpdfs01ns\\Shares\\FreightShare\\RUBY\\NAV Batch Import Files")]
        public string BatchLoadDirectory {
            get {
                return ((string)(this["BatchLoadDirectory"]));
            }
            set {
                this["BatchLoadDirectory"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\ausefpdfs01ns\\Shares\\Public\\DCOperations\\Lantech\\Orders\\New Orders")]
        public string LanTechExportDirectory {
            get {
                return ((string)(this["LanTechExportDirectory"]));
            }
            set {
                this["LanTechExportDirectory"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\ausefpdfs01ns\\Shares\\FreightShare\\RUBY\\NAV Batch Import Files")]
        public string BatchSaveDirectory {
            get {
                return ((string)(this["BatchSaveDirectory"]));
            }
            set {
                this["BatchSaveDirectory"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool AutoSplitZone {
            get {
                return ((bool)(this["AutoSplitZone"]));
            }
            set {
                this["AutoSplitZone"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool AutoSplitCartons {
            get {
                return ((bool)(this["AutoSplitCartons"]));
            }
            set {
                this["AutoSplitCartons"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("A,B")]
        public string CartonSplitString {
            get {
                return ((string)(this["CartonSplitString"]));
            }
            set {
                this["CartonSplitString"] = value;
            }
        }
    }
}
